<?php

namespace core\settings;

interface ArmorSettings
{
    const DEFENSE_COPPER_HELMET = 2;
    const DEFENSE_COPPER_CHESTPLATE = 6;
    const DEFENSE_COPPER_LEGGINGS = 5;
    const DEFENSE_COPPER_BOOTS = 2;
    const DURABILITY_COPPER_HELMET = 100;
    const DURABILITY_COPPER_CHESTPLATE = 100;
    const DURABILITY_COPPER_LEGGINGS = 100;
    const DURABILITY_COPPER_BOOTS = 100;

    const DEFENSE_PLATINUM_HELMET = 4;
    const DEFENSE_PLATINUM_CHESTPLATE = 9;
    const DEFENSE_PLATINUM_LEGGINGS = 7;
    const DEFENSE_PLATINUM_BOOTS = 4;
    const DURABILITY_PLATINUM_HELMET = 100;
    const DURABILITY_PLATINUM_CHESTPLATE = 100;
    const DURABILITY_PLATINUM_LEGGINGS = 100;
    const DURABILITY_PLATINUM_BOOTS = 100;

    const DEFENSE_EMERALD_HELMET = 3;
    const DEFENSE_EMERALD_CHESTPLATE = 8;
    const DEFENSE_EMERALD_LEGGINGS = 6;
    const DEFENSE_EMERALD_BOOTS = 3;
    const DURABILITY_EMERALD_HELMET = 100;
    const DURABILITY_EMERALD_CHESTPLATE = 100;
    const DURABILITY_EMERALD_LEGGINGS = 100;
    const DURABILITY_EMERALD_BOOTS = 100;

    const DEFENSE_ELECTRUM_HELMET = 5;
    const DEFENSE_ELECTRUM_CHESTPLATE = 10;
    const DEFENSE_ELECTRUM_LEGGINGS = 8;
    const DEFENSE_ELECTRUM_BOOTS = 5;
    const DURABILITY_ELECTRUM_HELMET = 100;
    const DURABILITY_ELECTRUM_CHESTPLATE = 100;
    const DURABILITY_ELECTRUM_LEGGINGS = 100;
    const DURABILITY_ELECTRUM_BOOTS = 100;

    const DEFENSE_WOODEN_HELMET = 1;
    const DEFENSE_WOODEN_CHESTPLATE = 2;
    const DEFENSE_WOODEN_LEGGINGS = 1;
    const DEFENSE_WOODEN_BOOTS = 1;
    const DURABILITY_WOODEN_HELMET = 100;
    const DURABILITY_WOODEN_CHESTPLATE = 100;
    const DURABILITY_WOODEN_LEGGINGS = 100;
    const DURABILITY_WOODEN_BOOTS = 100;

    const DEFENSE_SILVER_HELMET = 2;
    const DEFENSE_SILVER_CHESTPLATE = 6;
    const DEFENSE_SILVER_LEGGINGS = 5;
    const DEFENSE_SILVER_BOOTS = 2;
    const DURABILITY_SILVER_HELMET = 100;
    const DURABILITY_SILVER_CHESTPLATE = 100;
    const DURABILITY_SILVER_LEGGINGS = 100;
    const DURABILITY_SILVER_BOOTS = 100;

    const DEFENSE_PINK_GOLD_HELMET = 6;
    const DEFENSE_PINK_GOLD_CHESTPLATE = 11;
    const DEFENSE_PINK_GOLD_LEGGINGS = 9;
    const DEFENSE_PINK_GOLD_BOOTS = 6;
    const DURABILITY_PINK_GOLD_HELMET = 468;
    const DURABILITY_PINK_GOLD_CHESTPLATE = 1022;
    const DURABILITY_PINK_GOLD_LEGGINGS = 958;
    const DURABILITY_PINK_GOLD_BOOTS = 830;

    const DEFENSE_GOLDENWHITE_HELMET = 6;
    const DEFENSE_GOLDENWHITE_CHESTPLATE = 11;
    const DEFENSE_GOLDENWHITE_LEGGINGS = 9;
    const DEFENSE_GOLDENWHITE_BOOTS = 6;
    const DURABILITY_GOLDENWHITE_HELMET = 100;
    const DURABILITY_GOLDENWHITE_CHESTPLATE = 100;
    const DURABILITY_GOLDENWHITE_LEGGINGS = 100;
    const DURABILITY_GOLDENWHITE_BOOTS = 100;

    const DEFENSE_STEEL_HELMET = 6;
    const DEFENSE_STEEL_CHESTPLATE = 11;
    const DEFENSE_STEEL_LEGGINGS = 9;
    const DEFENSE_STEEL_BOOTS = 6;
    const DURABILITY_STEEL_HELMET = 100;
    const DURABILITY_STEEL_CHESTPLATE = 100;
    const DURABILITY_STEEL_LEGGINGS = 100;
    const DURABILITY_STEEL_BOOTS = 100;
}