<?php

namespace core\settings;

interface ToolSettings
{
    const DURABILITY_COPPER_PICKAXE = 1000;
    const DURABILITY_COPPER_AXE = 1000;
    const DURABILITY_COPPER_SHOVEL = 1000;
    const DURABILITY_COPPER_SWORD = 1000;
    const DURABILITY_COPPER_HOE = 1000;
    const ATTACK_COPPER_PICKAXE = 1;
    const ATTACK_COPPER_AXE = 2;
    const ATTACK_COPPER_SHOVEL = 1;
    const ATTACK_COPPER_SWORD = 5;
    const ATTACK_COPPER_HOE = 1;

    const DURABILITY_PLATINUM_PICKAXE = 1000;
    const DURABILITY_PLATINUM_AXE = 1000;
    const DURABILITY_PLATINUM_SHOVEL = 1000;
    const DURABILITY_PLATINUM_SWORD = 1000;
    const DURABILITY_PLATINUM_HOE = 1000;
    const ATTACK_PLATINUM_PICKAXE = 1;
    const ATTACK_PLATINUM_AXE = 2;
    const ATTACK_PLATINUM_SHOVEL = 1;
    const ATTACK_PLATINUM_SWORD = 5;
    const ATTACK_PLATINUM_HOE = 1;

    const DURABILITY_EMERALD_PICKAXE = 1000;
    const DURABILITY_EMERALD_AXE = 1000;
    const DURABILITY_EMERALD_SHOVEL = 1000;
    const DURABILITY_EMERALD_SWORD = 1000;
    const DURABILITY_EMERALD_HOE = 1000;
    const ATTACK_EMERALD_PICKAXE = 1;
    const ATTACK_EMERALD_AXE = 2;
    const ATTACK_EMERALD_SHOVEL = 1;
    const ATTACK_EMERALD_SWORD = 5;
    const ATTACK_EMERALD_HOE = 1;

    const DURABILITY_ELECTRUM_PICKAXE = 1000;
    const DURABILITY_ELECTRUM_AXE = 1000;
    const DURABILITY_ELECTRUM_SHOVEL = 1000;
    const DURABILITY_ELECTRUM_SWORD = 1000;
    const DURABILITY_ELECTRUM_HOE = 1000;
    const ATTACK_ELECTRUM_PICKAXE = 1;
    const ATTACK_ELECTRUM_AXE = 2;
    const ATTACK_ELECTRUM_SHOVEL = 1;
    const ATTACK_ELECTRUM_SWORD = 5;
    const ATTACK_ELECTRUM_HOE = 1;

    const DURABILITY_SILVER_PICKAXE = 1000;
    const DURABILITY_SILVER_AXE = 1000;
    const DURABILITY_SILVER_SHOVEL = 1000;
    const DURABILITY_SILVER_SWORD = 1000;
    const DURABILITY_SILVER_HOE = 1000;
    const ATTACK_SILVER_PICKAXE = 1;
    const ATTACK_SILVER_AXE = 2;
    const ATTACK_SILVER_SHOVEL = 1;
    const ATTACK_SILVER_SWORD = 5;
    const ATTACK_SILVER_HOE = 1;

    const DURABILITY_GOLDENPINK_PICKAXE = 1000;
    const DURABILITY_GOLDENPINK_AXE = 1000;
    const DURABILITY_GOLDENPINK_SHOVEL = 1000;
    const DURABILITY_GOLDENPINK_SWORD = 1000;
    const DURABILITY_GOLDENPINK_HOE = 1000;
    const ATTACK_GOLDENPINK_PICKAXE = 1;
    const ATTACK_GOLDENPINK_AXE = 2;
    const ATTACK_GOLDENPINK_SHOVEL = 1;
    const ATTACK_GOLDENPINK_SWORD = 5;
    const ATTACK_GOLDENPINK_HOE = 1;

    const DURABILITY_GOLDENWHITE_PICKAXE = 1000;
    const DURABILITY_GOLDENWHITE_AXE = 1000;
    const DURABILITY_GOLDENWHITE_SHOVEL = 1000;
    const DURABILITY_GOLDENWHITE_SWORD = 1000;
    const DURABILITY_GOLDENWHITE_HOE = 1000;
    const ATTACK_GOLDENWHITE_PICKAXE = 1;
    const ATTACK_GOLDENWHITE_AXE = 2;
    const ATTACK_GOLDENWHITE_SHOVEL = 1;
    const ATTACK_GOLDENWHITE_SWORD = 5;
    const ATTACK_GOLDENWHITE_HOE = 1;

    const DURABILITY_STEEL_PICKAXE = 1000;
    const DURABILITY_STEEL_AXE = 1000;
    const DURABILITY_STEEL_SHOVEL = 1000;
    const DURABILITY_STEEL_SWORD = 1000;
    const DURABILITY_STEEL_HOE = 1000;
    const ATTACK_STEEL_PICKAXE = 1;
    const ATTACK_STEEL_AXE = 2;
    const ATTACK_STEEL_SHOVEL = 1;
    const ATTACK_STEEL_SWORD = 5;
    const ATTACK_STEEL_HOE = 1;


    const DURABILITY_WOODEN_DOUBLEPICKAXE = 1000;
    const DURABILITY_WOODEN_DOUBLEAXE = 1000;
    const DURABILITY_WOODEN_SPEAR = 1000;
    const DURABILITY_WOODEN_BIGSWORD = 1000;
    const DURABILITY_WOODEN_DOUBLEHOE = 1000;
    const DURABILITY_WOODEN_KNIFE = 1000;
    const DURABILITY_WOODEN_MULTITOOL = 1000;
    const DURABILITY_WOODEN_SICKLE = 1000;
    const DURABILITY_WOODEN_HAMMER = 1000;
    const DURABILITY_WOODEN_MULTITOOLS = 1000;
    const ATTACK_WOODEN_DOUBLEPICKAXE = 1;
    const ATTACK_WOODEN_DOUBLEAXE = 1;
    const ATTACK_WOODEN_SPEAR = 1;
    const ATTACK_WOODEN_BIGSWORD = 1;
    const ATTACK_WOODEN_DOUBLEHOE = 1;
    const ATTACK_WOODEN_KNIFE = 1;
    const ATTACK_WOODEN_MULTITOOL = 1;
    const ATTACK_WOODEN_SICKLE = 1;
    const ATTACK_WOODEN_HAMMER = 1;
    const ATTACK_WOODEN_MULTITOOLS = 1;
}