<?php

namespace core\blocks\blocks\biomes\spectral;

use core\blocks\vanilla\Farmland;
use customiesdevs\customies\block\CustomiesBlockFactory;
use pocketmine\entity\Entity;
use pocketmine\event\block\FarmlandHydrationChangeEvent;
use pocketmine\math\Facing;

class SpectralFarmland extends Farmland
{
    protected function recalculateCollisionBoxes(): array
    {
        return parent::recalculateCollisionBoxes(); // TODO: Change the autogenerated stub
    }

    public function onEntityLand(Entity $entity) : ?float{
        return null;
    }

    public function onNearbyBlockChange() : void{
        if($this->getSide(Facing::UP)->isSolid()){
            $this->position->getWorld()->setBlock($this->position, CustomiesBlockFactory::getInstance()->get("goldrush:spectral_dirt"));
        }
    }


    public function onRandomTick() : void{
        $world = $this->position->getWorld();

        //this property may be updated by canHydrate() - track this so we know if we need to set the block again
        $oldWaterPositionIndex = $this->getWaterPositionIndex();
        $changed = false;

        if(!$this->canHydrate()){
            if($this->wetness > 0){
                $event = new FarmlandHydrationChangeEvent($this, $this->wetness, $this->wetness - 1);
                $event->call();
                if(!$event->isCancelled()){
                    $this->wetness = $event->getNewHydration();
                    $world->setBlock($this->position, $this, false);
                    $changed = true;
                }
            }else{
                $world->setBlock($this->position, CustomiesBlockFactory::getInstance()->get("goldrush:spectral_dirt"));
                $changed = true;
            }
        }elseif($this->wetness < self::MAX_WETNESS){
            $event = new FarmlandHydrationChangeEvent($this, $this->wetness, self::MAX_WETNESS);
            $event->call();
            if(!$event->isCancelled()){
                $this->wetness = $event->getNewHydration();
                $world->setBlock($this->position, CustomiesBlockFactory::getInstance()->get("goldrush:spectral_dirt_farmland_wet"), false);
                $changed = true;
            }
        }

        if(!$changed && $oldWaterPositionIndex !== $this->getWaterPositionIndex()){
            //ensure the water square index is saved regardless of whether anything else happened
            $world->setBlock($this->position, $this, false);
        }
    }
}